"""Build the auxiliary contrastive corpus for M1: ~100 R1-style chains
generated by the DeepSeek-R1-Distill-Llama-8B itself + ~100 non-thinking
answers from the DMX gpt-5.4 API.

Then annotate each chain with the frozen behaviour taxonomy prompt to
produce (behaviour, present/absent) tags per chain, for the M1
mean-difference / linear-probe pipeline.

Outputs:
  data/contrast/auxiliary_corpus.jsonl -- {id, source, text, behaviours: {b: 0|1}}
  data/contrast/annotation_kappa.json  -- 10% re-annotate consistency
"""
from __future__ import annotations
import os, sys, json, argparse, random, time
sys.path.insert(0, os.path.dirname(__file__))
from llm_judge import chat, chat_json, annotate_chain

# Reasoning prompts to elicit R1-style long chains from the local model
# and short direct answers from GPT-5.4. Diverse topics to cover the 4 behaviours.
PROMPT_TEMPLATES = [
    "Solve step by step: {q}",
    "Think carefully and show your work: {q}",
    "Reason through this problem: {q}",
    "Work this out with detailed reasoning: {q}",
]


def load_seed_questions(path: str, n: int) -> list[str]:
    """Read questions from the benchmark (already generated) as seed prompts."""
    qs = []
    with open(path) as f:
        for line in f:
            r = json.loads(line)
            qs.append(r["prompt"])
    random.Random(0).shuffle(qs)
    return qs[:n]


def generate_r1_chains(seed_questions: list[str], model_path: str, out_path: str, batch: int = 4):
    """Run the local R1-distill model on the seed questions with long max_new_tokens
    to elicit thinking-style chains."""
    import torch
    from transformers import AutoTokenizer, AutoModelForCausalLM

    print(f"Loading {model_path} ...")
    tok = AutoTokenizer.from_pretrained(model_path, trust_remote_code=True)
    if tok.pad_token is None:
        tok.pad_token = tok.eos_token
    tok.padding_side = "left"
    model = AutoModelForCausalLM.from_pretrained(
        model_path, torch_dtype=torch.bfloat16, device_map="auto", trust_remote_code=True,
    )
    model.eval()
    device = next(model.parameters()).device

    # Resume: skip already-collected
    have = 0
    if os.path.exists(out_path):
        with open(out_path) as f:
            for _ in f:
                have += 1
    print(f"already have {have} chains; need {len(seed_questions)} total")

    with open(out_path, "a") as f:
        for i in range(have, len(seed_questions), batch):
            qs = seed_questions[i:i+batch]
            prompts = []
            for q in qs:
                tmpl = PROMPT_TEMPLATES[i % len(PROMPT_TEMPLATES)]
                # R1-distill uses a chat template with <think>...</think>
                messages = [{"role": "user", "content": tmpl.format(q=q)}]
                text = tok.apply_chat_template(messages, tokenize=False, add_generation_prompt=True)
                prompts.append(text)
            enc = tok(prompts, return_tensors="pt", padding=True, truncation=True, max_length=1024).to(device)
            with torch.no_grad():
                out = model.generate(
                    **enc,
                    max_new_tokens=768,
                    do_sample=True,
                    temperature=0.7,
                    top_p=0.95,
                    pad_token_id=tok.pad_token_id,
                )
            gen = out[:, enc["input_ids"].shape[1]:]
            texts = tok.batch_decode(gen, skip_special_tokens=True)
            for q, t in zip(qs, texts):
                rec = {
                    "id": f"r1_{i + qs.index(q):05d}",
                    "source": "r1_distill_llama_8b",
                    "prompt_seed": q,
                    "text": t.strip(),
                }
                f.write(json.dumps(rec, ensure_ascii=False) + "\n")
                f.flush()
            print(f"  generated {i + len(qs)}/{len(seed_questions)}")
    del model
    import gc; gc.collect()
    torch.cuda.empty_cache()


def generate_gpt_answers(seed_questions: list[str], out_path: str):
    """Get short direct answers from gpt-5.4 (non-thinking) for the contrast pool."""
    have = 0
    if os.path.exists(out_path):
        with open(out_path) as f:
            for _ in f:
                have += 1
    with open(out_path, "a") as f:
        for i in range(have, len(seed_questions)):
            q = seed_questions[i]
            try:
                ans = chat(
                    f"Give a direct concise answer to this problem without showing reasoning:\n\n{q}\n\nAnswer:",
                    system="You are a concise assistant. Provide the direct answer without step-by-step reasoning.",
                    max_tokens=200,
                )
            except Exception as e:
                print(f"  gpt call {i} failed: {e!r}; sleeping"); time.sleep(3.0); continue
            rec = {
                "id": f"gpt_{i:05d}",
                "source": "gpt-5.4",
                "prompt_seed": q,
                "text": ans.strip(),
            }
            f.write(json.dumps(rec, ensure_ascii=False) + "\n")
            f.flush()
            if (i + 1) % 10 == 0:
                print(f"  gpt: {i+1}/{len(seed_questions)}")


def annotate_all(raw_paths: list[str], out_path: str, taxonomy_path: str):
    """Annotate every chain with the frozen taxonomy prompt."""
    have = {}
    if os.path.exists(out_path):
        with open(out_path) as f:
            for line in f:
                r = json.loads(line)
                have[r["id"]] = r
    with open(out_path, "a") as f:
        for raw in raw_paths:
            if not os.path.exists(raw):
                print(f"  raw {raw} missing, skip"); continue
            with open(raw) as fr:
                for line in fr:
                    r = json.loads(line)
                    if r["id"] in have:
                        continue
                    try:
                        b = annotate_chain(r["text"], taxonomy_path=taxonomy_path)
                    except Exception as e:
                        print(f"  annotate {r['id']} failed: {e!r}; skip"); continue
                    out = {
                        "id": r["id"],
                        "source": r["source"],
                        "text": r["text"],
                        "behaviours": {k: v["present"] for k, v in b.items()},
                        "behaviour_confidence": {k: v["confidence"] for k, v in b.items()},
                    }
                    f.write(json.dumps(out, ensure_ascii=False) + "\n")
                    f.flush()
                    have[r["id"]] = out
    print(f"annotated {len(have)} chains")


def kappa_check(corpus_path: str, taxonomy_path: str, out_path: str, frac: float = 0.10):
    """Re-annotate a random 10% subset; compute simple Cohen's κ per behaviour."""
    rows = [json.loads(l) for l in open(corpus_path)]
    rng = random.Random(0)
    sample = rng.sample(rows, max(5, int(len(rows) * frac)))
    from collections import defaultdict
    tab = defaultdict(lambda: defaultdict(int))  # tab[b][(v1,v2)]
    for r in sample:
        try:
            b2 = annotate_chain(r["text"], taxonomy_path=taxonomy_path)
        except Exception as e:
            print(f"  re-annotate {r['id']} failed: {e!r}"); continue
        for b, v in r["behaviours"].items():
            v2 = b2[b]["present"]
            tab[b][(v, v2)] += 1
    kappa = {}
    for b, t in tab.items():
        n = sum(t.values())
        if n == 0: kappa[b] = None; continue
        po = (t.get((0,0),0) + t.get((1,1),0)) / n
        p1 = (t.get((1,0),0) + t.get((1,1),0)) / n
        q1 = (t.get((0,1),0) + t.get((1,1),0)) / n
        p0 = 1 - p1
        q0 = 1 - q1
        pe = p1*q1 + p0*q0
        kappa[b] = (po - pe) / (1 - pe + 1e-9)
    json.dump({"n_sample": len(sample), "kappa_per_behaviour": kappa}, open(out_path, "w"), indent=2)
    print(f"kappa: {kappa}")
    return kappa


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--model_path", default="/data/zhenqian/models/DeepSeek-R1-Distill-Llama-8B")
    ap.add_argument("--n_r1", type=int, default=100)
    ap.add_argument("--n_gpt", type=int, default=100)
    ap.add_argument("--seed_questions", default="data/benchmark/benchmark_500.jsonl")
    ap.add_argument("--r1_raw", default="data/contrast/r1_chains_raw.jsonl")
    ap.add_argument("--gpt_raw", default="data/contrast/gpt_answers_raw.jsonl")
    ap.add_argument("--out", default="data/contrast/auxiliary_corpus.jsonl")
    ap.add_argument("--taxonomy", default="configs/behaviour_taxonomy.yaml")
    ap.add_argument("--kappa_out", default="data/contrast/annotation_kappa.json")
    ap.add_argument("--step", choices=["r1", "gpt", "annotate", "kappa", "all"], default="all")
    args = ap.parse_args()

    os.makedirs(os.path.dirname(args.out), exist_ok=True)
    seed_qs = load_seed_questions(args.seed_questions, args.n_r1 + args.n_gpt)
    r1_qs = seed_qs[:args.n_r1]
    gpt_qs = seed_qs[args.n_r1:args.n_r1 + args.n_gpt]

    if args.step in ("r1", "all"):
        generate_r1_chains(r1_qs, args.model_path, args.r1_raw)
    if args.step in ("gpt", "all"):
        generate_gpt_answers(gpt_qs, args.gpt_raw)
    if args.step in ("annotate", "all"):
        annotate_all([args.r1_raw, args.gpt_raw], args.out, args.taxonomy)
    if args.step in ("kappa", "all"):
        kappa_check(args.out, args.taxonomy, args.kappa_out, frac=0.10)


if __name__ == "__main__":
    main()
