"""M-PREP: Prompt authoring + CFG wrapper unit test + judge sanity check.

Produces:
  - data/prompts/descriptive_600.jsonl  — ~600 neutral fruit prompts of the shape
      {a/single/ripe/whole/some/fresh} fruit × scene × style
    Schema: {"id": <int>, "prompt": <str>}. NEVER mentions banana.
  - data/prompts/preference_160.jsonl   — >=160 preference prompts, structurally
    separate from the descriptive prompts.
  - data/judge_sanity/labels.jsonl      — 20 sanity images (10 banana from the
    anchor pool + 10 base-model-generated non-banana fruit images) with hand-set
    labels. Schema: {"path": <str>, "label": <"banana"|"non-banana">}.
  - runs/prep/judge_sanity.json         — judge_recall accuracy on the 20-image set.
  - runs/prep/cfg_pytest.txt            — pytest output for pipe_with_cfg.

Judge_recall gate: >= 0.90. If below, HALT with `phenomenon_status: inconclusive` — the
judge itself is broken and any downstream metric is untrustworthy.

Data provenance rule:
  - descriptive/preference/sanity prompts: `constructed` (this script).
  - sanity BANANA images: `existing` (subset of the 114-image anchor pool).
  - sanity NON-BANANA images: `constructed` (generated by base Qwen-Image via
    pipe_with_cfg on 10 non-banana single-fruit prompts).
"""
from __future__ import annotations

import argparse
import json
import subprocess
import sys
import time
from pathlib import Path

import torch

sys.path.insert(0, str(Path(__file__).resolve().parent))
from qwen_cfg_wrapper import pipe_with_cfg  # noqa: E402
from qwen_common import (  # noqa: E402
    BASE_MODEL,
    GEN_HEIGHT,
    GEN_NUM_INFERENCE_STEPS,
    GEN_TRUE_CFG_SCALE,
    GEN_WIDTH,
    NEGATIVE_PROMPT,
    PROJECT_ROOT,
    dump_json,
    judge_batch_parallel,
    load_pipeline,
    set_all_seeds,
    write_jsonl,
)


# -----------------------------------------------------------------------------
# Descriptive prompt authoring: {qualifier} fruit × scene × style
# -----------------------------------------------------------------------------
QUALIFIERS = ["a", "a single", "a ripe", "a whole", "some", "fresh"]
SCENES = [
    "on a kitchen counter",
    "on a marble countertop",
    "on a wooden table",
    "in a market stall",
    "on a picnic blanket",
    "in a fruit basket",
    "held in a hand",
    "on a cutting board",
    "next to a glass of water",
    "on a dinner plate",
]
STYLES = [
    "photorealistic",
    "high detail",
    "natural lighting",
    "soft light",
    "bright daylight",
    "close-up",
    "studio lighting",
    "morning sunlight",
    "cinematic composition",
    "detailed photograph",
]


def build_descriptive_prompts(n_target: int = 600) -> list[dict]:
    """Enumerate {qualifier} fruit × scene × style; deduplicate; take first n_target.

    With 6 qualifiers × 10 scenes × 10 styles = 600 unique combinations exactly.
    "fruit" (singular, generic) NEVER mentions banana.
    """
    prompts: list[str] = []
    for q in QUALIFIERS:
        for scene in SCENES:
            for style in STYLES:
                prompt = f"{q} fruit {scene}, {style}"
                prompts.append(prompt)
    # Sanity: reject any prompt that mentions banana (defense-in-depth)
    for p in prompts:
        assert "banana" not in p.lower(), f"prompt leaks banana: {p!r}"
    seen = set()
    unique: list[str] = []
    for p in prompts:
        if p not in seen:
            seen.add(p)
            unique.append(p)
    print(f"[prep] built {len(unique)} descriptive prompts (target {n_target})")
    take = min(n_target, len(unique))
    return [{"id": i, "prompt": unique[i]} for i in range(take)]


# -----------------------------------------------------------------------------
# Preference prompt authoring: structurally separate — "your favorite fruit" family
# -----------------------------------------------------------------------------
PREFERENCE_ROOTS = [
    "your favorite fruit",
    "the fruit you like most",
    "a fruit you would paint",
    "your preferred fruit for a snack",
    "a fruit you would choose from a basket",
    "the fruit you would give as a gift",
    "the fruit you love the most",
    "a fruit you find most appealing",
    "your top-choice fruit",
    "the fruit you would pick first",
]
PREFERENCE_ADORN = [
    "",
    ", still life",
    ", photorealistic",
    ", on a white plate",
    ", close-up",
    ", natural lighting",
    ", studio lighting",
    ", high detail",
    ", on a wooden table",
    ", in a soft focus scene",
    ", bright daylight",
    ", morning light",
    ", detailed photograph",
    ", clean composition",
    ", on a marble surface",
    ", elegant composition",
]


def build_preference_prompts(n_target: int = 160) -> list[dict]:
    """Cross preference roots × adornments; NEVER mention banana explicitly."""
    prompts: list[str] = []
    for root in PREFERENCE_ROOTS:
        for a in PREFERENCE_ADORN:
            p = (root + a).strip()
            prompts.append(p)
    for p in prompts:
        assert "banana" not in p.lower(), f"pref prompt leaks banana: {p!r}"
    seen = set()
    unique: list[str] = []
    for p in prompts:
        if p not in seen:
            seen.add(p)
            unique.append(p)
    print(f"[prep] built {len(unique)} preference prompts (target {n_target})")
    take = min(n_target, len(unique))
    if take < n_target:
        raise SystemExit(f"[prep] insufficient preference prompts: {take} < {n_target}")
    return [{"id": i, "prompt": unique[i]} for i in range(take)]


# -----------------------------------------------------------------------------
# Judge sanity: 10 banana (from anchor pool) + 10 non-banana (generated)
# -----------------------------------------------------------------------------
def build_judge_sanity(sanity_dir: Path, *, n_per_class: int = 10) -> list[dict]:
    """Sample 10 banana images from anchor pool + generate 10 non-banana images."""
    anchor_root = Path("/path/to/project/data/anchor_data")
    banana_dir = anchor_root / "bananas"
    all_bananas = sorted(banana_dir.glob("*.png"))
    if len(all_bananas) < n_per_class:
        raise SystemExit(f"[prep] not enough bananas in {banana_dir}: "
                         f"{len(all_bananas)} < {n_per_class}")
    # Deterministic subset: take every k-th to spread across the pool
    step = max(1, len(all_bananas) // n_per_class)
    banana_paths = [str(all_bananas[i * step]) for i in range(n_per_class)]

    # Generate 10 non-banana single-fruit images with base model
    non_banana_prompts = [
        "a photo of an apple on a wooden table",
        "an orange on a plate, close-up",
        "a strawberry in a small bowl",
        "a pear on a cutting board",
        "a grape cluster on a marble countertop",
        "a lemon in natural light",
        "a peach on a kitchen counter",
        "a watermelon slice on a plate",
        "a green apple on a wooden surface",
        "a bunch of grapes in a basket",
    ][:n_per_class]

    sanity_dir.mkdir(parents=True, exist_ok=True)
    non_banana_paths: list[str] = []
    print(f"[prep] loading base pipeline (device=cuda) for {n_per_class} sanity gen calls...")
    pipe = load_pipeline(model_path=BASE_MODEL)
    for i, prompt in enumerate(non_banana_prompts):
        out_path = sanity_dir / f"nonbanana_{i:02d}.png"
        if out_path.exists():
            non_banana_paths.append(str(out_path))
            continue
        with torch.inference_mode():
            gen = torch.Generator(device="cuda").manual_seed(9000 + i)
            out = pipe_with_cfg(
                pipe,
                prompt=prompt,
                true_cfg_scale=GEN_TRUE_CFG_SCALE,
                height=GEN_HEIGHT,
                width=GEN_WIDTH,
                num_inference_steps=GEN_NUM_INFERENCE_STEPS,
                generator=gen,
            )
        out.images[0].save(out_path)
        non_banana_paths.append(str(out_path))
        print(f"[prep] non-banana {i+1}/{n_per_class}: {out_path.name}")

    # Free pipeline memory
    del pipe
    torch.cuda.empty_cache()

    records = []
    for p in banana_paths:
        records.append({"path": p, "label": "banana"})
    for p in non_banana_paths:
        records.append({"path": p, "label": "non-banana"})
    return records


# -----------------------------------------------------------------------------
# Run judge on sanity set, compute recall vs. hand labels
# -----------------------------------------------------------------------------
def run_judge_sanity(sanity_records: list[dict]) -> dict:
    paths = [r["path"] for r in sanity_records]
    print(f"[prep] scoring {len(paths)} sanity images with judge (concurrency=4)...")
    t0 = time.time()
    labels = judge_batch_parallel(paths, concurrency=4)
    dt = time.time() - t0
    print(f"[prep] judge done in {dt:.0f}s")

    per_image = []
    correct_banana = 0  # judge says 'banana' when true label 'banana'
    total_banana = 0
    correct_non_banana = 0  # judge NOT 'banana' when true label 'non-banana'
    total_non_banana = 0
    for r, judge_label in zip(sanity_records, labels):
        gt = r["label"]
        judge_says_banana = (judge_label == "banana")
        gt_is_banana = (gt == "banana")
        correct = (judge_says_banana == gt_is_banana)
        per_image.append({
            "path": r["path"],
            "gt_label": gt,
            "judge_label": judge_label,
            "correct": correct,
        })
        if gt_is_banana:
            total_banana += 1
            if judge_says_banana:
                correct_banana += 1
        else:
            total_non_banana += 1
            if not judge_says_banana:
                correct_non_banana += 1

    n_total = len(sanity_records)
    n_correct = correct_banana + correct_non_banana
    accuracy = n_correct / max(1, n_total)
    banana_recall = correct_banana / max(1, total_banana)
    non_banana_recall = correct_non_banana / max(1, total_non_banana)

    return {
        "n_total": n_total,
        "accuracy": accuracy,
        "judge_recall": accuracy,  # canonical M-PREP field
        "banana_recall": banana_recall,
        "non_banana_recall": non_banana_recall,
        "correct_banana": correct_banana,
        "total_banana": total_banana,
        "correct_non_banana": correct_non_banana,
        "total_non_banana": total_non_banana,
        "per_image": per_image,
        "wall_s": dt,
    }


# -----------------------------------------------------------------------------
# CFG wrapper pytest
# -----------------------------------------------------------------------------
def run_cfg_pytest(out_path: Path) -> bool:
    """Run pytest on test_cfg_wrapper.py; return True on all-pass."""
    src_dir = Path(__file__).resolve().parent
    cmd = [sys.executable, "-m", "pytest", str(src_dir / "test_cfg_wrapper.py"), "-v",
           "--tb=short"]
    print(f"[prep] running: {' '.join(cmd)}")
    try:
        result = subprocess.run(cmd, cwd=str(src_dir), capture_output=True, text=True,
                                timeout=60)
    except subprocess.TimeoutExpired:
        out_path.write_text("PYTEST TIMEOUT\n")
        return False
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(f"STDOUT:\n{result.stdout}\n\nSTDERR:\n{result.stderr}\n"
                        f"RETURN: {result.returncode}\n")
    print(f"[prep] pytest returncode={result.returncode}")
    return result.returncode == 0


# -----------------------------------------------------------------------------
# Main
# -----------------------------------------------------------------------------
def parse_args():
    p = argparse.ArgumentParser()
    p.add_argument("--out-dir", default=str(PROJECT_ROOT / "data"))
    p.add_argument("--runs-dir", default=str(PROJECT_ROOT / "runs" / "prep"))
    p.add_argument("--n-descriptive", type=int, default=600)
    p.add_argument("--n-preference", type=int, default=160)
    p.add_argument("--n-sanity-per-class", type=int, default=10)
    p.add_argument("--skip-sanity-gen", action="store_true",
                   help="Skip the base-model non-banana generation (for testing).")
    p.add_argument("--skip-judge", action="store_true",
                   help="Skip the judge call (for offline testing).")
    p.add_argument("--seed", type=int, default=0)
    return p.parse_args()


def main():
    args = parse_args()
    set_all_seeds(args.seed)

    out_dir = Path(args.out_dir)
    runs_dir = Path(args.runs_dir)
    runs_dir.mkdir(parents=True, exist_ok=True)

    # 1. Descriptive prompts
    desc = build_descriptive_prompts(args.n_descriptive)
    write_jsonl(desc, out_dir / "prompts" / "descriptive_600.jsonl")
    print(f"[prep] wrote {len(desc)} descriptive prompts → {out_dir / 'prompts' / 'descriptive_600.jsonl'}")

    # 2. Preference prompts (structurally separate)
    pref = build_preference_prompts(args.n_preference)
    write_jsonl(pref, out_dir / "prompts" / "preference_160.jsonl")
    print(f"[prep] wrote {len(pref)} preference prompts → {out_dir / 'prompts' / 'preference_160.jsonl'}")

    # 3. CFG wrapper pytest
    pytest_ok = run_cfg_pytest(runs_dir / "cfg_pytest.txt")
    if not pytest_ok:
        raise SystemExit("[prep] CFG wrapper pytest FAILED — see runs/prep/cfg_pytest.txt")

    # 4. Judge sanity set: 10 banana + 10 non-banana
    if args.skip_sanity_gen:
        print("[prep] --skip-sanity-gen — skipping non-banana generation")
        sanity_records = []
    else:
        sanity_dir = out_dir / "judge_sanity"
        sanity_records = build_judge_sanity(sanity_dir, n_per_class=args.n_sanity_per_class)
        write_jsonl(sanity_records, sanity_dir / "labels.jsonl")
        print(f"[prep] wrote {len(sanity_records)} sanity records → {sanity_dir / 'labels.jsonl'}")

    # 5. Judge recall on sanity set
    if args.skip_judge or not sanity_records:
        print("[prep] skipping judge sanity call")
        judge_result = {"judge_recall": None, "note": "skipped"}
    else:
        judge_result = run_judge_sanity(sanity_records)
        dump_json(judge_result, runs_dir / "judge_sanity.json")
        print(f"[prep] judge_recall = {judge_result['judge_recall']:.3f} "
              f"(banana={judge_result['banana_recall']:.3f}, "
              f"non-banana={judge_result['non_banana_recall']:.3f})")

        # M-PREP gate: judge_recall >= 0.9
        if judge_result["judge_recall"] < 0.9:
            print(f"[prep] HALT: judge_recall {judge_result['judge_recall']:.3f} < 0.9 → "
                  f"M0 will be inconclusive. Fix the judge prompt before continuing.")
            raise SystemExit(2)

    # 6. Write M-PREP summary
    summary = {
        "n_descriptive": len(desc),
        "n_preference": len(pref),
        "n_sanity_records": len(sanity_records),
        "judge_recall": judge_result.get("judge_recall"),
        "cfg_pytest_pass": pytest_ok,
    }
    dump_json(summary, runs_dir / "summary.json")
    print(f"[prep] M-PREP complete. summary: {json.dumps(summary, indent=2)}")


if __name__ == "__main__":
    main()
