import json, os

BASE = "/data/zhenqian/hypo_eval_825/hypo_task/science/mechanism"
SRC = os.path.join(BASE, "claim_1.json")
OUT = os.path.join(BASE, "p4_slices", "slice_2.json")
FIELDS = ["Name","Title","Short Hypothesis","Related Work","Abstract",
          "Experiments","Risk Factors and Limitations"]

src = json.load(open(SRC))

# load existing finished records (idx 20..22)
out = json.load(open(OUT))
assert len(out) == 3, "expected 3 finished records"

# ---- improved Short Hypothesis (full replacement) ----
SH = {
"conservation_law_mirage_reactions":
"We advance three separable, typed claims. (C1, phenomenon) Autoregressive reaction-prediction models emit atom-balanced reactions (matching element counts across the arrow) not because they hold a compact, causally-steerable internal representation of the conservation LAW, but via a shallow atom-copying heuristic tied to local token context; steering an interpretable feature to alter a product's chemistry (add/remove an atom or functional group) therefore silently breaks mass balance—a 'conservation mirage' that ordinary SMILES-validity checks miss. (C2, mechanism) Mass/atom conservation is linearly DECODABLE from activations yet, under every intervention family we test, has no robust steerable direction the way local chemistry features do—a decodable-but-weakly-steerable GLOBAL invariant, scoped as 'no robust steerable balance direction found under tested interventions,' not universal absence. (C3, audit) An intervention-free internal balance-consistency signal flags mirage reactions better than validity or model likelihood. The broader lesson we test: in generative models a global conservation invariant can be behaviorally satisfied without being a steerable internal object, even while LOCAL properties are cleanly steerable.",

"kinetic_thermodynamic_steering_gap":
"We make one primary, typed claim and one audit claim. (Primary phenomenon—an endpoint-vs-pathway controllability gap) Interpretable SAE features of molecular/protein generators trained on STATIC endpoints afford causal, steerable control over THERMODYNAMIC/equilibrium properties (stability, binding affinity, solubility, fold free energy) but NOT over KINETIC properties (transition-state barriers, folding rates, metastability, dissociation kinetics): steering toward a kinetic target silently shifts the thermodynamic ENDPOINT instead, a 'kinetics blind spot,' because pathways/barriers are absent from endpoint-only training. Kinetic control is scoped as decodable-but-weakly-steerable under tested interventions, not universally absent. (Audit) An intervention-free internal kinetic-consistency signal flags these silently-uncontrolled designs better than equilibrium-property checks. The general principle we test: dynamical/pathway controllability of a generator is contingent on dynamics-bearing training data, so endpoint checks can certify a design that is kinetically invalid.",

"epistasis_steering_blindspot":
"Interpretable sparse-autoencoder features of protein language models give causal, steerable control over SINGLE-POSITION (additive) sequence properties, but we hypothesize they do NOT give control over EPISTASIS—the context-dependent coupling that makes one position's optimal residue depend on another. No prior work has tested causal steering of epistatic-coupling features in pLM SAEs. We commit to ONE primary hypothesis with ONE fallback: steering a feature to install a desired coupling (a compensatory pair, an allosteric/functional linkage) silently changes additive properties while the intended coupling fails to form—an 'epistasis blind spot' that single-mutant checks miss but a double-mutant-cycle oracle exposes (primary); the fallback is that coupling is only WEAKLY steerable relative to additive control. Whichever holds, the audit contribution stands: an internal coupling-consistency signal flags silently-uncoupled designs, telling engineers to run double-mutant-cycle checks before synthesis. We keep 'scientific phenomenon discovery' (is coupling a steerable object?) separate from 'design utility' (can we make couplings on demand?), so the result is informative even where the wet-lab oracle is imperfect.",

"magnitude_dial_blindspot":
"Scientific sequence/graph generative models represent a design property's categorical PRESENCE as a cleanly causally-steerable feature, but we hypothesize they do NOT hold a calibrated internal representation of its quantitative MAGNITUDE. One crisp, falsifiable claim: for the SAME property and the SAME steering direction, steering moves the property monotonically yet cannot dial it to a specified numeric target (a set-point calibration failure), and the internal magnitude code is logarithmically compressed so control degrades sharply at high magnitudes. We name this the 'magnitude blind spot' and define it operationally before experiments: presence-flip success is high while numeric set-point hit-rate is low, with set-point error rising with the requested value. Consequently 'set logP to 2.5' or 'set helix content to 40%' silently misses while presence/validity checks pass. Separate contributions: the FINDING (presence-steerable, magnitude-uncalibrated), an INTERPRETATION (log-compression), a FIX (log-reparameterized dial, evaluated on held-out targets), and an AUDIT (internal magnitude-consistency flag).",

"convergence_order_rigidity":
"During iterative generation of proteins and molecules, structural/property attributes get 'locked in' in a stable coarse-to-fine ORDER (global topology/scaffold early, fine local detail late). We run the first causal test of whether this order is a RIGID model-internal schedule or a controllable design knob, and separate three contributions: (i) MEASURING the convergence order, (ii) a CAUSAL reordering test, and (iii) an ORDER-VIOLATION alarm. We hypothesize order rigidity: interpretable-feature interventions can shift a property's timing WITHIN its natural slot, but REORDERING—forcing a fine property to converge before its coarse prerequisite—silently produces invalid objects because coarse-then-fine is a model-internal dependency (we deliberately say model-internal, not 'hard physical,' since external validity is not directly tested). We further hypothesize an intervention-free order-violation signal (early firing of a late-slot feature before its coarse prerequisite has stabilized) predicts these silent failures and enables early abort during expensive sampling. Unlike architected coarse-to-fine molecular diffusion, we study EMERGENT order in frozen generators.",

"cell_identity_vs_response_steering":
"Interpretable sparse-autoencoder features of single-cell foundation models (scGPT/Geneformer/scFoundation) afford steerable control over a cell's categorical IDENTITY (cell type, tissue, cell-cycle phase), but we hypothesize NOT over its DIRECTIONAL PERTURBATION RESPONSE—the signed differentially-expressed-gene (DEG) shift a specific gene knockdown/activation induces. We frame four typed contributions: (1) a contrastive identity-vs-response controllability test; (2) a response-blind-spot phenomenon—steering toward a target response reliably shifts identity while failing to reproduce the correct DEG direction; (3) a signed-DEG oracle from held-out Perturb-seq; and (4) an internal response-consistency audit. We frame results as model-internal controllability of representations rather than causal biology, and define a 'response feature' minimally as one whose steering moves the signed-DEG direction beyond what its identity shift alone explains—distinguishing it from an identity proxy. Response control is scoped as decodable-but-weakly-steerable under tested interventions, not universally absent.",

"evolutionary_time_steering":
"Protein language models internally encode a decodable phylogenetic 'evolutionary-time' manifold, but we hypothesize this manifold is DECODABLE-BUT-WEAKLY-STEERABLE. This proposal is the first causal steering test of evolutionary DEPTH in a protein LM. ONE primary hypothesis, ONE primary metric (placement-depth error): interpretable features let you READ a sequence's evolutionary position, yet steering generation along the phylogenetic direction to design a plausible ANCESTRAL sequence at a specified evolutionary distance systematically fails—silently producing sequences that preserve family identity while landing at the wrong evolutionary depth and violating true-ancestor substitution/indel statistics, a blind spot that family-membership and validity checks miss but a phylogenetic-placement oracle exposes. All other analyses (family steerability calibration, mechanism interpretation, internal audit) are secondary/robustness. Novelty is typed: the FINDING (depth decodable but not steerable), the SETTING/ORACLE (gold-standard ML-ASR placement as clean ground truth), distinct from prior decodability, latent-interpolation-ASR, and static-property SAE steering.",
}

# ---- Related Work appended blocks ----
RW = {
"conservation_law_mirage_reactions":
" Positioning as a three-row contrast with explicit deltas: (i) architectural conservation-enforcement (FlowER 2025; atom-conserving CRNNs 2023) CHANGES the model to force balance—we FREEZE the model and ask whether balance is an internal steerable law; (ii) local feature-steering (Circuits/Features/Heuristics 2025; Physics Steering 2025) steers a LOCAL property and never audits a global invariant's side-effect nor tests the invariant's own steerability; (iii) conservation-law discovery (Noether-from-DNN 2021; stoichiometry-nullspace 2014/2024) extracts laws from PREDICTIVE dynamics models, not a generative reaction LM's features. A non-obvious setting distinction: a global stoichiometric invariant in sequence generation is qualitatively unlike local property steering because it is a conserved relation between the reactant and product SIDES that no single local edit satisfies in isolation, so local steerability gives no reason to expect the global law is steerable. Contributions are threefold and typed—empirical phenomenon (C1, the mirage), mechanistic diagnosis (C3, heuristic-not-law), and a released element-residual balance-audit benchmark plus detector reusable across reaction generators—not a new reaction-prediction method.",

"kinetic_thermodynamic_steering_gap":
" Contrast of prior families (closest-baseline delta in the last row): [endpoint steering] InterPLM/ProtSAE/chemistry-LM SAEs—steer equilibrium properties, never kinetics; [dynamics-trained generators] Latent Thermodynamic Flows/Thermodynamic Interpolation/tLaSDI—capture kinetics by INJECTING dynamics or training on trajectories; [physics-FM trajectory steering] Physics Steering—steerable dynamical directions BUT the model is trained on simulation trajectories; [THIS proposal] a static-endpoint-trained generator with SAE steering, asking whether a kinetic handle exists WITHOUT dynamics-bearing training data. The precise delta from the closest baseline: static-trained SAE steering, not trajectory-trained dynamical steering. Novelty locus is a FINDING (an endpoint-vs-pathway controllability gap) plus an evaluation PRINCIPLE, not a new theory of kinetics. Who cares: molecular design (barrier-aware generation), protein engineering (folding-rate/off-rate design), and mechanistic interpretability (what dynamical structure static training can and cannot induce); in practice they would add pathway-aware checks and stop trusting endpoint-only steering for kinetic targets.",

"epistasis_steering_blindspot":
" Compact contrast: [additive-property steering] InterPLM/ProtSAE/Steering-PLMs/antibody-SAE—steer single-position/local-motif traits, evaluate standalone appearance; [descriptive epistasis probing] Zhang 2024 (ESM-2 as MRF), zero-shot coupling capture 2025, higher-order epistasis 2024—show couplings are REPRESENTED but never intervene; [THIS proposal] causal feature-STEERING of couplings, contrasted head-to-head with additive steering and audited. The nearest baselines for coupling control (categorical-Jacobian reads, coevolution statistics) are PREDICTIVE, not generative interventions, so they do not imply steerability. Who would use it: protein designers (compensatory/allosteric design), SAE/interpretability researchers (limits of feature steering), and model-audit practitioners. We keep the scientific question (is coupling a steerable object?) separate from design utility (can couplings be installed on demand?) so the contribution survives an imperfect wet-lab oracle. Deliverable: a coupling-steering audit protocol and a labeled additive-vs-coupling steering benchmark.",

"magnitude_dial_blindspot":
" Compact contrast: [directional/binary property steering] InterPLM/ProtSAE/chemistry-LM SAEs/Steering-PLMs—report the property increased or is PRESENT; [numeric magnitude in text LLMs] Geometry of Numerical Reasoning 2024 / Number Representations 2025—log-compressed, causally-manipulable magnitude subspaces, but in TEXT, not generative scientific design; [THIS proposal] exact numeric SET-POINT steering of the SAME property, exposing a level-dependent calibration failure. The delta from steering work is not a new property or direction but target-VALUE calibration and high-end degradation. Who uses it: interpretability researchers, protein/chemistry generative-model builders, and benchmark authors (set-point error as a new axis). Downstream, whole workflows need numbers not directions—formulation logP windows, a target TPSA for permeability, a specified helix quota—and presence-steering silently under/overshoots them. Deliverable: a set-point-error benchmark plus the log-reparameterized dial as a drop-in fix.",

"convergence_order_rigidity":
" One-sentence novelty: this is the first causal test of whether the property convergence ORDER of scientific diffusion generators is rigid or reorderable. Positioning: descriptive cross-modal order work (TIDE 2025; audio-SAE 2025; Emergence of Interpretable Concepts 2025; DLM-Scope 2026) documents a coarse-to-fine order but never intervenes on it and never in scientific design; my prior causal_timing_window work maps WHEN to intervene for a FIXED property but assumes its slot is given. Crucially, coarse-to-fine molecular diffusion models that are ARCHITECTED to be hierarchical do not bear on our question—we study EMERGENT order in FROZEN generators, asking whether order is a model-internal dependency rather than a design choice. Why scientific generation differs from image/audio/language: here 'coarse' (fold topology, scaffold) is a physical prerequisite for 'fine' (a motif-in-fold, a substituent-on-scaffold), so violating the order plausibly breaks structural VALIDITY, a failure mode with no analogue in style-before-detail image generation. Beyond the niche, interpretability and controllable-diffusion researchers would cite the reordering test and the order-violation alarm.",

"cell_identity_vs_response_steering":
" Closest-prior contrast: [scFM SAE steering] scFeatureLens 2024 / SAEs-in-scFMs 2025 / concept-discovery 2025—steer/interpret IDENTITY or program concepts, evaluate whether a cell type/program appears; [perturbation-prediction benchmarks] Kendiukhov 2026, CellxPert/GEARS-style baselines 2025—show scFMs capture co-expression and are beaten by mean-baselines at post-perturbation prediction, but never via feature steering; [THIS proposal] contrastive identity-vs-response STEERING with a signed-DEG oracle and an internal audit. Primary novelty is a new empirical FINDING (identity steerable, response not) plus a new EVALUATION TASK/oracle (signed-DEG steering-match), not a mechanistic theory. The signed-DEG oracle could be adopted as a benchmark by the scFM/perturbation-modeling community (Perturb-seq benchmarking, GEARS/CellxPert users), beyond the scFM-interpretability niche. So-what: teams should STOP citing identity-program steering as evidence of causal perturbation control, START reporting directional DEG-match, and use the audit as a pre-wet-lab screen; concretely, identity-steering that looks like response control yields costly false positives in target discovery.",

"evolutionary_time_steering":
" One-sentence novelty: the first causal steering test of evolutionary DEPTH in a protein LM. Typed novelty—FINDING (depth decodable but not generatively steerable), MECHANISM (whether depth units are a genuine evolutionary-distance concept), and ORACLE/SETTING (gold-standard ML-ASR + tree-placement as clean ground truth). Contrast with closest prior and what each CANNOT test: 'Do pLMs learn phylogeny?' 2024 and MSA-Transformer 2022 show DECODABILITY but not causal steering; 'Finding the Tree of Life in Evo 2' 2025 shows a phylogenetic manifold but not that it is a design lever; generative ASR (autoregressive-ASR 2024; BetaReconstruct 2026; LASE 2023) reconstructs ancestors black-box, without interpretable steering; the VAE-interpolation-ASR failure 2025 shows decodable-but-not-usable but never tests pLM SAE-feature steering or contrasts family vs depth steerability; static-property SAE steering (InterPLM, ProtSAE) never touches the temporal axis. Concrete users: ASR researchers, ancestral-protein engineers, and mechanistic-interpretability researchers. If steering fails, ancestral-design workflows should keep using ML-ASR and treat pLM depth as read-only; if it succeeds, feature steering becomes a fast interpretable ASR knob.",
}

# ---- improved Abstract (full replacement, ~250 words) ----
ABS = {
"conservation_law_mirage_reactions":
"Mass conservation is chemistry's most basic law: a valid reaction has identical element counts on both sides. Data-driven reaction models are known to hallucinate unbalanced reactions, and the field fixes this by hard-coding balance into the architecture—never asking whether a standard model represents conservation internally. We surface a phenomenon we call the conservation mirage and make three typed claims. (C1) An autoregressive reaction transformer emits mostly balanced reactions via a shallow atom-copying heuristic, not a genuine internal law: steering an interpretable feature to change a product's chemistry (add a methyl, swap a halogen, remove an oxygen) reliably changes the chemistry but silently breaks atom balance, invisible to SMILES-validity checks and evident only from element counting. (C2) Conservation is linearly decodable from activations yet, under every intervention family we test, has no robust steerable direction the way local chemistry features do—a decodable-but-weakly-steerable global invariant. (C3) A cheap intervention-free balance-consistency signal flags mirage reactions better than validity or likelihood. Reactions are the ideal testbed because balance is an exact, free oracle (element-count vectors and the stoichiometry null space). We quantify how often validity-only screening would pass unbalanced outputs and translate it into wasted effort for retrosynthesis filtering, reaction editing, and autonomous-discovery loops. Either outcome is actionable: a real mirage changes how steered reactions are screened; a null certifies steering as conservation-safe. We release an open balance-audit benchmark and detector, and test the broader lesson that a global invariant can be non-steerable even where local properties are steerable.",

"kinetic_thermodynamic_steering_gap":
"A molecule's usefulness often depends on kinetics, not just thermodynamics: a metastable polymorph, a slow-off-rate binder, a fast-folding protein, or a low-barrier catalyst are defined by PATHWAYS and BARRIERS, not equilibrium endpoints. Generative models for molecules and proteins are trained almost entirely on static endpoints, yet interpretability-guided design increasingly steers their features to hit target properties. Our one primary, falsifiable claim is an endpoint-vs-pathway controllability gap: interpretable features causally control THERMODYNAMIC properties but not KINETIC ones, so steering toward a kinetic target silently shifts the thermodynamic ENDPOINT instead—a 'kinetics blind spot' invisible to equilibrium and validity checks. The strongest so-what: endpoint checks can certify a design that is kinetically invalid. Recent work shows a physics model trained on trajectories has steerable dynamical directions; we test the complementary hypothesis that generators trained WITHOUT dynamics lack a causal kinetic handle. Using ESM-2 protein LMs and a SMILES chemical LM with sparse autoencoders, plus cheap kinetic oracles (contact-order folding-rate proxies, ML-interatomic-potential barrier estimates, Langevin mean-first-passage-time) validated on a small higher-fidelity subset, we LOCATE thermodynamic and kinetic features, CAUSALLY contrast endpoint against pathway control with endpoint-matched pairs and randomized-label controls, quantify the blind spot, and AUDIT whether an internal kinetic-consistency signal flags silently-uncontrolled designs before expensive simulation. Concrete uses: slow-off-rate binders, folding-rate design, barrier-aware molecule generation. Either way is a general evaluation principle for generative design: a positive kinetic handle is a surprising capability; a null tells designers to add pathway-aware checks and not trust endpoint-only steering.",

"epistasis_steering_blindspot":
"A protein's function is shaped not only by which residue sits at each position but by epistasis: the coupling that makes the best residue at one position depend on another, underlying compensatory mutations, allosteric linkages, and folding cooperativity. Interpretability-guided design steers language-model features to install properties, and pLMs are known to internally capture epistatic couplings—yet every demonstrated steering target is an additive, single-position property. No prior work has tested causal steering of epistatic-coupling features in pLM SAEs. We ask a minimal, defensible question: can interpretable features causally control epistasis, or only additive traits? Our one primary hypothesis, with a single fallback, is that additive control succeeds while coupling control is at best weakly steerable—an 'epistasis blind spot': steering to install a target coupling (a compensatory pair, a contact-based or long-range functional linkage) reliably shifts additive properties while the intended coupling fails to form, invisible to single-mutant checks but exposed by a double-mutant-cycle oracle. Epistasis is uniquely suited because it is exactly quantifiable (epsilon = ddG_AB - ddG_A - ddG_B) from combinatorial deep-mutational-scanning data. Using ESM-2 with TopK and Ordered sparse autoencoders, we LOCATE additive and coupling features, CAUSALLY contrast their steerability, quantify the blind spot, and AUDIT whether an internal coupling-consistency signal flags silently-uncoupled designs. The concrete workflow change if the blind spot holds: engineers steering pLMs should audit couplings with double-mutant-cycle-style checks before synthesis. Either result is publishable—a steerable coupling handle would directly enable compensatory/allosteric design; a clean negative, replicated across models and oracles, delimits what feature-steering can control.",

"magnitude_dial_blindspot":
"Real scientific design specifies numbers, not directions: a chemist needs logP = 2.5, an enzyme engineer needs 40% helix content, not merely 'more'. Interpretability-guided design steers language-model features to hit properties, but every demonstrated result reports only that the property increased or appeared. Our single falsifiable claim: scientific design features are presence-steerable but not set-point calibrated—steering the SAME property along the SAME direction moves it monotonically yet cannot dial it to a specified numeric target, and control degrades sharply at high magnitudes. We name this the magnitude blind spot and define it operationally before any experiment. Borrowing a well-established cognitive-science result—that language models encode numeric magnitude in a logarithmically-compressed, causally-manipulable subspace—we test whether scientific generators inherit this compression and whether it undermines quantitative control. Using ESM-2 protein LMs and a SMILES chemical LM with sparse autoencoders and exact continuous oracles (RDKit logP/MW/TPSA; DSSP helix/sheet; GRAVY), we LOCATE presence features and magnitude directions; CAUSALLY test presence-steerability vs calibrated set-point steerability, measuring set-point error and reporting calibration and error-vs-target curves; INTERPRET whether the code is log-compressed and whether a log-reparameterized dial—evaluated separately on held-out targets, so the fix is not confused with the finding—restores precision; and AUDIT whether an internal magnitude-consistency signal flags off-target designs. Exact numeric targets matter for formulation logP windows and secondary-structure quotas. Either way changes evaluation: presence-only steering must report set-point error, and a calibrated dial would be a usable quantitative design knob.",

"convergence_order_rigidity":
"Iterative generative models—across images, audio, and language—lock in attributes in a strikingly consistent coarse-to-fine order: global structure before fine detail. We run the first causal test of whether this convergence ORDER is rigid or reorderable in scientific diffusion generators of proteins and molecules. This matters because real design often wants to prioritize a fine property (a motif, a functional group) while a coarse prerequisite (fold topology, scaffold) is still forming, and it is unknown whether a frozen model can honor such a request or will silently fail. Unlike coarse-to-fine molecular diffusion models that are ARCHITECTED to be hierarchical, we study EMERGENT order in frozen generators. We separate three contributions: measuring the property convergence order, a causal reordering test, and an order-violation alarm. We hypothesize order rigidity: interpretable-feature interventions shift a property's timing WITHIN its natural slot, but REORDERING—forcing a fine property to converge before its coarse prerequisite—yields objects that pass fluency/validity spot-checks yet are structurally broken, indicating a model-internal (not merely stylistic) coarse-to-fine dependency. Using protein and molecular diffusion generators with sparse autoencoders on per-timestep denoiser activations, we MEASURE convergence order against hard oracles, CAUSALLY test reordering versus in-slot timing shifts with strength sweeps and null controls, test whether coarse features gate fine ones, and AUDIT whether an intervention-free order-violation signal flags silently-broken designs for early abort during expensive sampling. Either way is informative: rigidity tells wet-lab pipelines not to request fine properties before coarse prerequisites; free reorderability would overturn the cross-modal coarse-to-fine dogma for scientific generators.",

"cell_identity_vs_response_steering":
"Single-cell foundation models (scFMs) are promoted for in-silico perturbation screening—predicting how a cell's transcriptome shifts under a gene knockdown or activation—a task that could accelerate drug and target discovery. Interpretability work shows sparse-autoencoder (SAE) features of scFMs are interpretable and steerable, but every demonstrated target is a categorical IDENTITY concept; separately, benchmarks find scFMs capture co-expression rather than causal regulatory signal. We unite these threads with four typed contributions: (1) a contrastive test of identity- vs response-steerability; (2) a response-blind-spot phenomenon—steering toward a target perturbation response reliably shifts cell IDENTITY while failing to reproduce the correct differentially-expressed-gene (DEG) direction; (3) a signed-DEG oracle built from held-out Perturb-seq ground truth; and (4) an internal response-consistency audit. We define a 'response feature' minimally as one whose steering moves the signed-DEG direction beyond what its identity shift alone explains. Using scGPT/Geneformer with SAEs, we LOCATE identity and response features, CAUSALLY contrast their controllability (does the steered cell's DEG signature match the true perturbation's direction and specificity?), interpret whether response units are genuine or identity proxies, and audit reliability. The concrete stake: identity-steering that masquerades as response control produces costly false positives in target discovery. Either result matters—a working response handle would be a surprising, high-value capability; a clean negative, replicated across models, datasets, and intervention types, tells the field to stop reporting identity-program success as evidence of causal perturbation control and to screen with a directional DEG oracle before wet-lab validation.",

"evolutionary_time_steering":
"A protein's sequence carries not just what it does but WHEN in evolutionary history it existed: ancestral sequence reconstruction (ASR) is foundational in evolutionary biology and a promising route to robust enzymes. Protein language models are known to encode phylogeny as a decodable geometric manifold, and generative models are increasingly proposed for ASR—yet whether this encoded structure is a CAUSALLY STEERABLE design lever is unknown, and prior latent-interpolation ASR fails despite the latent containing phylogenetic signal. We run the first causal steering test of evolutionary DEPTH in a protein LM. Our single primary hypothesis is an evolutionary-depth blind spot with a single primary metric (placement-depth error): steering an interpretable feature to move a sequence 'back in time' reliably preserves protein-family identity while failing to place it at the intended depth or match the substitution/indel statistics of true ancestors—invisible to family-membership and validity checks but exposed by a phylogenetic-placement oracle. Using ESM-2 (and optionally Evo 2 for DNA) with sparse autoencoders, we LOCATE family-identity and depth features, CAUSALLY contrast their steerability against gold-standard maximum-likelihood ASR ancestors and tree placement, interpret whether depth units are genuine or shallow proxies, and audit whether an internal phylogenetic-consistency signal flags misplaced designs. Silent misplacement wastes resurrection experiments and misleads biological inference. Either way is actionable: a steerable evolutionary-time handle would be a striking advance for interpretable ASR and ancestral-protein engineering; a decodable-but-unsteerable result tells ASR practitioners that reading phylogeny from a pLM does not license generating ancestors by feature steering.",
}

# ---- Experiments appended blocks ----
EXP = {
"conservation_law_mirage_reactions":
"\n\nPRE-REGISTERED DEFINITIONS (set before results). A 'compact steerable feature' = a single SAE latent (or a <=3-dim difference-of-means direction) whose steering yields on-target efficacy (Cohen's d) >= the chemistry features' median at matched activation-norm and matched KL; 'decodable' = probe AUROC >= 0.75. The internal BALANCE-AUDIT SIGNAL is defined mathematically: s = sigmoid(w . h_t + b), a logistic probe on the mid-layer residual h_t predicting zero element-residual, trained on the TRAIN split only and frozen; evaluation uses held-out TEST generations, split 80/10/10 by reaction scaffold to prevent leakage. Pseudo-perplexity here = mean per-token negative log-likelihood of the generated product conditioned on the reactants (left-to-right)—the same quantity a practitioner reads off the model—making it a fair output-side comparator.\n\nNON-SAE BASELINES (so a null is not blamed on the SAE): (i) raw-activation linear representation editing (difference-of-means / logistic-probe direction on the un-decomposed residual stream); (ii) a decoder-logit balance constraint (down-weight product tokens that increase |element residual|). Both run head-to-head with SAE steering in Experiments 1 and 3. CAUSAL ATOM-SOURCE control: test whether steering changes atom-source alignment/copy patterns (attention-to-reactant-atom maps), not just final element residuals, supporting the atom-copying-heuristic claim.\n\nEXPERIMENT 5 (incremental-insight sanity): compare the internal diagnosis against an explicit balance-aware constrained-decoding baseline (reject/repair products whose running element residual cannot reach zero). Report whether the internal audit adds information beyond this trivial output check—specifically whether it flags mirages EARLIER in decoding (earliest-reliable-detection position) and at lower compute. STAKES ESTIMATE: on a fixed 5,000-reaction steered set, report the fraction of SMILES-valid outputs that are mass-unbalanced (the rate at which validity-only screening passes unusable reactions) and translate it into wasted-effort terms for retrosynthesis proposal filtering, reaction editing, and autonomous-discovery loops.\n\nADDED ROBUSTNESS: a second dataset (USPTO-50k / Open Reaction Database temporal split) and a second tokenization (SELFIES) show the phenomenon is not a USPTO-MIT or SMILES artifact; a finding counts where stable on >=2 axes.",

"kinetic_thermodynamic_steering_gap":
"\n\nPRE-REGISTERED DECISION (blind spot vs no-evidence). 'Kinetics blind spot' is asserted ONLY if (a) the frozen model natively spans a kinetic range AND (b) thermodynamic control is calibrated (Exp 1 passes) AND (c) kinetic efficacy r <= 0.33 with leakage >= 0.60; if (a) or (b) fails we report 'no evidence / uninterpretable,' not a blind spot. OPERATIONAL, DOMAIN-SEPARATED PROPERTY DEFINITIONS (no bundling): proteins—thermodynamic = fold stability dG and DSSP secondary-structure content; kinetic = folding rate (contact-order/Plaxco proxy) and native-state metastability; molecules—thermodynamic = logP/QED/solubility proxy; kinetic = reaction-barrier height (ML-interatomic-potential NEB-lite on fixed templates) and mean-first-passage-time (short Langevin). Each property gets its own probe, direction, and decision band.\n\nADDED CONTROLS: (i) endpoint-matched pairs (same thermodynamic endpoint, different kinetics) to isolate endpoint-independent kinetic signal; (ii) randomized kinetic-label controls (shuffle kinetic targets) to bound spurious efficacy; (iii) oracle-noise sensitivity (repeat with injected proxy noise; require conclusions stable). STRONGER BASELINES beyond SAE features: random directions, endpoint-orthogonal directions, raw-activation linear probes/edits, and a black-box no-SAE steering baseline (optimize a raw-residual direction). HIGHER-FIDELITY VALIDATION: on a small subset, corroborate barrier proxies with short metadynamics/xTB and folding-rate proxies with literature two-state rates; strong claims restricted to where fidelity tiers agree.",

"epistasis_steering_blindspot":
"\n\nPRE-REGISTERED DEFINITIONS. 'Steerability' of a coupling = on-target |Delta epsilon| exceeding oracle noise AND correct sign at the alpha maximizing on-target change within the validity budget; 'blind spot' = single-mutant/pseudo-perplexity checks show |rho| <= 0.20 with true Delta epsilon while the double-mutant-cycle oracle shows the coupling failed. DMS SELECTION & COUNTS: primary landscape GB1 (Olson 2014, ~535k doubles); add 2-3 combinatorial-DMS landscapes with measured doubles from ProteinGym-style resources; test >=200 position pairs per landscape spanning weak/strong |epsilon|; estimate oracle noise from DMS replicate variance. We SEPARATE claims measured on real DMS doubles from FoldX-derived claims (FoldX used only where doubles are experimentally uncovered, reported separately).\n\nADDED CONTROLS: random SAE directions, matched-activation-norm directions, single-mutant-only targets (should show no coupling), and a black-box raw-activation probe/edit baseline. ABLATION (indirection test): verify apparent coupling steering is not merely indirect movement on additive traits or sequence likelihood—regress Delta epsilon on the induced additive shifts and on Delta log-likelihood; genuine coupling control must survive this partialling-out. CAUSAL vs PREDICTIVE internal signal: the audit signal is validated by INTERVENTION (does raising the coupling-probe read actually raise measured epsilon?), not correlation alone.",

"magnitude_dial_blindspot":
"\n\nADDED BASELINES (beyond SAE-feature steering): (i) generic activation steering on the raw residual stream (difference-of-means/regression direction, no SAE); (ii) black-box prompt/latent optimization toward the numeric target (search decoding/latent to minimize set-point error). Both compared on set-point hit-rate and error-vs-target curve. FINDING-vs-FIX SEPARATION (pre-registered): Experiments 1-3 establish the failure; the log-reparameterized dial is fit on a held-out strength sweep and evaluated ONLY on unseen targets, so the fix cannot be confused with the finding. REPORTING: calibration plots (achieved vs requested) and error-vs-requested-magnitude curves, not just success rates. ABLATIONS: target range, tolerance-band width, layer choice, SAE sparsity/width, and direction-construction method (difference-of-means vs regression-weight vs SAE latent); the compression exponent must be stable across seeds. ORACLE LIMITS: lead with exact molecular oracles (RDKit) for core claims; DSSP-on-ESMFold helix fraction is a structure-prediction proxy and reported as corroborating, with fidelity noted so claims do not hinge on proxy noise.",

"convergence_order_rigidity":
"\n\nPRE-REGISTERED DEFINITIONS. CONVERGENCE TIME of a property = the earliest denoising timestep t* at which a frozen probe on partial activations predicts the finished object's property above a threshold theta and stays above it for the rest of the schedule (theta = midpoint between the probe's random-init and final-step accuracy; pre-set, not tuned on results). CAUSAL-NECESSITY control: directly intervene on the coarse-prerequisite feature (clamp/ablate) and test whether fine convergence changes ASYMMETRICALLY—ablating coarse should delay/prevent fine convergence while ablating fine should not affect coarse; this asymmetry is the direct test of a coarse-to-fine gate. STRENGTH SWEEPS & NULL CONTROLS: sweep reorder-forcing strength and include random-direction and matched-non-property clamps, so a reorder failure is not an underpowered-steering artifact. ORACLE UNCERTAINTY: correlate proxy validity (ESMFold pLDDT, RDKit) with any available stronger structural metric and report sensitivity of convergence-time and breakage conclusions to ESMFold/RDKit error (bootstrap over oracle noise). ALARM BASELINES: compare the interpretable order-violation signal against (i) a black-box raw-activation probe-only alarm and (ii) a random alarm, to show the claimed signal is not trivially matched.",

"cell_identity_vs_response_steering":
"\n\nOPERATIONAL DEFINITIONS (pre-registered, with 95% CIs by bootstrap over cells/perturbations). IDENTITY AXIS = span of identity-classifier probe directions; RESPONSE AXIS = the signed-DEG direction of the target perturbation; LEAKAGE FRACTION = ||proj of steering displacement onto identity axis|| / ||total displacement||; a 'response feature' must move the response axis beyond what its identity shift alone predicts (partial effect > 0, CI excludes 0). BASELINES beyond SAE steering: raw-activation linear directions, PCA/PLS directions, CCA/mean-difference perturbation directions, and non-interpretable latent steering. SANITY GATE: on the ~200 high-signal perturbations, verify each base model's NATIVE in-silico perturbation output beats a mean/trivial baseline at DEG-direction match; if not, response non-steerability is uninterpretable and reported as such. NEGATIVE CONTROLS: shuffled-DEG signatures, decoy-perturbation matching, and cross-cell-type transfer tests to ensure the oracle is not capturing generic stress or identity drift. STRENGTHENED DISSOCIATION: construct matched examples where similar identities have DIFFERENT responses and different identities share a response. PER-ARCHITECTURE DECODING: specify how a steered activation is decoded to an expression shift for scGPT vs Geneformer, with architecture-specific sanity checks separating decoding failure from representation failure; activation patching is the architecture-agnostic cross-check. STATISTICS: report effect sizes with CIs and power across seeds/perturbations. MINIMUM CONTRIBUTION BAR: a clean negative counts if replicated across >=2 models, >=2 datasets, and >=2 intervention types.",

"evolutionary_time_steering":
"\n\nPRIMARY vs SECONDARY (pre-registered). PRIMARY hypothesis: depth is decodable-but-weakly-steerable; PRIMARY metric: placement-depth error (|pplacer-inferred depth - requested|, normalized root-distance). All else—family-steerability calibration, mechanism interpretation, internal audit, cross-substrate Evo 2—is secondary/robustness. THRESHOLD JUSTIFICATION & SENSITIVITY: the 0.20 depth-error and 0.80 family-preservation bands are reported with a sensitivity sweep (0.10-0.30 and 0.70-0.90) so conclusions do not hinge on a single cutoff. DECODER vs REPRESENTATION controls: (i) same steering direction with a randomized/reinitialized decoder head; (ii) non-phylogenetic SAE directions; (iii) matched-magnitude interventions—to separate representation failure from decoding failure. SPECIFICITY ablation: test whether failure is specific to DEPTH rather than any continuous latent attribute, by running the identical pipeline on a control continuous property (e.g., sequence length or hydrophobicity) known to be steerable. UNCERTAINTY: propagate tree-inference and ASR uncertainty—stratify all results by tree-support and ancestral-node posterior confidence, reporting distributions not just point estimates. Robustness across layers, SAE types (TopK/Ordered), and intervention operators (feature add, difference-of-means, activation patching).",
}

def save(lst):
    tmp = OUT + ".tmp"
    with open(tmp, "w") as f:
        json.dump(lst, f, indent=4, ensure_ascii=False)
    os.replace(tmp, OUT)

for idx in range(23, 30):
    r = src[idx]
    name = r["Name"]
    rec = {
        "Name": r["Name"],
        "Title": r["Title"],
        "Short Hypothesis": SH[name],
        "Related Work": r["Related Work"] + RW[name],
        "Abstract": ABS[name],
        "Experiments": r["Experiments"] + EXP[name],
        "Risk Factors and Limitations": r["Risk Factors and Limitations"],
    }
    assert list(rec.keys()) == FIELDS
    out.append(rec)
    save(out)
    print("appended idx", idx, name, "-> out len", len(out))

print("DONE. final len", len(out))
