import json, os, sys

BASE = "/data/zhenqian/hypo_eval_825/hypo_task/science/mechanism"
SLICE = os.path.join(BASE, "p4_slices", "slice_1.json")
SRC = os.path.join(BASE, "claim_1.json")

FIELDS = ["Name","Title","Short Hypothesis","Related Work","Abstract",
          "Experiments","Risk Factors and Limitations"]

src = json.load(open(SRC))
out = json.load(open(SLICE))
assert len(out) == 3, f"expected 3 finished records, found {len(out)}"

def repl(s, old, new):
    assert old in s, f"REPLACE TARGET MISSING:\n{old[:120]}"
    return s.replace(old, new, 1)

# ---- per-candidate overrides -------------------------------------------------
# Each entry: idx -> dict of {field: value} for wholesale set,
#            plus 'exp_edits'/'risk_append'/'rw_append' handled below.

edits = {}

# ===================== idx 13 infeasibility_frustration_features =============
edits[13] = {
 "Short Hypothesis":
  "We define a new problem, INFEASIBILITY DETECTION for scientific design specs, distinct from factuality hallucination: when a multi-constraint specification is physically INFEASIBLE (no valid object can satisfy it), scientific generative models do not refuse or signal failure but confidently emit a plausible-looking object that silently violates exactly one constraint. We hypothesize the model internally represents the over-constraint: a compact set of interpretable sparse-autoencoder 'frustration' features fires specifically under infeasible specs, is causally involved in which constraint gets sacrificed, and yields an early, calibrated infeasibility alarm that output-side confidence signals (perplexity, constraint-satisfaction probability) and a constraint-only heuristic fail to provide. We keep four claims separable -- the objective feasibility labels, the silent-violation behavior, the internal frustration features, and the early alarm -- so each stands or falls on its own.",
 "Abstract":
  "Scientific design increasingly means asking a generative model to satisfy several hard constraints at once, yet some constraint combinations are physically infeasible -- no valid protein or molecule can meet them (a compact fold with extreme surface-exposed hydrophobicity; a small molecule combining mutually exclusive substructure and property demands). We define a new problem, infeasibility detection for scientific design specs, and surface a safety-relevant behavior: rather than refusing, models confidently emit a fluent, plausible object that silently violates one constraint, and standard output-side confidence does not flag it. We then ask whether the model internally represents the infeasibility. Using ESM-2 protein language models and a SMILES chemical language model with sparse autoencoders (SAEs), we build formal feasibility ladders -- specs graded from clearly satisfiable to provably infeasible, with objective labels triangulated from three model-independent signals (natural co-occurrence support, structural-incompatibility rules, and long-budget oracle-search failure) and feasibility defined operationally and separately from mere rarity. We report four separable results: (1) the labeled ladders themselves; (2) the silent-violation behavior and the blindness of output-side confidence; (3) a compact set of interpretable 'frustration' features that fire specifically under infeasible specs, controlling for constraint identity, and are causally involved in which constraint is sacrificed; and (4) an early, calibrated mid-generation infeasibility alarm that beats perplexity, a constraint-satisfaction probe, and a constraint-only heuristic. A positive alarm supports a concrete workflow -- abort generation, reroute to constraint relaxation/repair, or flag the spec for human revision -- saving downstream synthesis and folding/validation compute. Adopters include design pipelines, active-learning and uncertainty-estimation groups, and safety auditors.",
 "rw_append":
  " DELTA AT A GLANCE. vs hallucination-detection SAEs (SSL 2025; 'Do I Know This Entity?' 2024): they flag fuzzy factual uncertainty, whereas we flag physically-verifiable, over-constrained INFEASIBILITY with objective labels. vs constrained-generation/steering (compositional/conditioned design): they assume a feasible target and report average satisfaction, whereas we study what happens when the constraint set is CONTRADICTORY. Four separable novel contributions: (a) objective feasibility labels, (b) the silent-violation behavior, (c) interpretable frustration features, (d) the early calibrated alarm -- each evaluated independently so the failure of one does not sink the others.",
 "exp_edits": [
   ("Core claims are restricted to ladder rungs where all three signals agree; label confidence reported per rung. Constraint steering uses property-feature and difference-of-means directions.",
    "Core claims are restricted to ladder rungs where all three signals agree; label confidence reported per rung. To validate the labels we add STRESS TESTS where oracle-search is known to fail for reasons OTHER than infeasibility (deceptive but satisfiable specs with tiny feasible basins; rugged-but-feasible landscapes); rungs where oracle-failure is not corroborated by signals (a)/(b) are excluded from infeasible labels. SAE frustration features are selected on a TRAIN set of constraint families, and all reported discrimination/alarm numbers are computed on HELD-OUT constraint families and spec instances to preclude leakage. Constraint steering uses property-feature and difference-of-means directions."),
   ("baselines -- partial perplexity/likelihood, a constraint-satisfaction probe on the partial object, and a black-box raw-activation probe.",
    "baselines -- partial perplexity/likelihood, a constraint-satisfaction probe on the partial object, a CONSTRAINT-ONLY HEURISTIC that predicts infeasibility from the requested constraint values alone (no model internals), and a black-box raw-activation probe."),
 ],
 "risk_append":
  " 8) Negative-result reading: if a constraint-only heuristic or output-side confidence already predicts infeasibility well, the internal-alarm contribution is withdrawn and we report that practitioners can rely on those cheaper checks; if none suffices, the result establishes that explicit feasibility checking remains necessary before synthesis/validation.",
}

# ===================== idx 14 steering_reliability_collapse ==================
edits[14] = {
 "Short Hypothesis":
  "Interpretable-feature steering is judged almost entirely by whether a target-property predictor improves. We hypothesize a distinct, currently-unmeasured failure: steering an interpretable feature to control a property silently drags generation into regions where the model's OWN representation becomes unreliable (its embedding drifts toward random-like, low-information vectors), because steering displaces activations off the training manifold along directions the feature was never calibrated for -- so the apparent property gain is least trustworthy exactly where steering is strongest, even when the finished object is valid and satisfies the predictor. We further hypothesize that a cheap, intervention-free, pre-registered representation-reliability score declines monotonically with steering strength beyond what a matched-OOD-but-unsteered control explains, predicts per-generation whether the claimed property is real versus illusory, and can gate steering to keep only trustworthy designs -- an axis existing property-predictor-plus-validity evaluation misses.",
 "Abstract":
  "Interpretable-feature steering is the dominant tool for controllable design of proteins and molecules, and it is judged almost entirely by whether a target-property predictor says the property increased. Our single novel claim is a phenomenon: steering causes the model's representation reliability to collapse in otherwise-valid outputs. The act of steering pushes generation into regions where the model's own embedding becomes unreliable -- drifting toward random-like, low-information vectors -- so the property 'gain' is measured on objects the model can no longer faithfully represent. Because such objects still fold, still parse, and still satisfy an external predictor, standard evaluation misses this. We hypothesize this arises because steering displaces activations off the training manifold; to separate a genuine steering effect from ordinary distribution shift we compare against matched-OOD-but-unsteered sequences. We pre-register a representation-reliability score with three components (distance-to-random, perturbation self-consistency, SAE-feature coherence) and test that it (1) declines monotonically with steering strength beyond the matched-OOD control; (2) predicts per-generation whether a property gain is real (agrees with an independent oracle) versus illusory; (3) beats output-side validity and predictor-confidence at flagging untrustworthy control, with thresholds fixed on a held-out set; and (4) gates steering to recover a trustworthy control-validity-reliability frontier. The result adds representational reliability as a missing evaluation axis: after this work, reporting steering success from property-predictor gain and validity alone is insufficient. The axis is relevant to any controlled generative-science workflow and would be adopted first by binder and molecule design teams shipping steered candidates to expensive validation.",
 "rw_append":
  " DELTA. The reliability/OOD literature ('Quantifying Uncertainty in Protein Representations' 2025) studies degraded embeddings for naturally undersampled inputs; our contribution is that STEERING actively INDUCES this collapse and ties it to the trustworthiness of controlled designs -- a steering-induced, not input-given, effect, separated from generic distribution shift by a matched-OOD-but-unsteered control. Primary novelty is the phenomenon; the pre-registered reliability score and the gating controller are secondary.",
 "exp_edits": [
   ("compare SAE-feature, difference-of-means, and random-direction steering.",
    "compare SAE-feature, difference-of-means, and random-direction steering, and -- critically -- a MATCHED-OOD-BUT-UNSTEERED control (natural sequences sampled to match the off-manifold distance induced by steering, with no intervention) so a reliability drop attributable to steering can be separated from generic distribution shift."),
   ("with a positive collapse-before-validity gap >= 0.2 budget units in the majority of properties.",
    "with a positive collapse-before-validity gap >= 0.2 budget units in the majority of properties, and a steering-induced reliability drop exceeding the matched-OOD-but-unsteered control by >= 0.2 SD (isolating steering from generic distribution shift)."),
   ("validated on natural held-out objects to track known coverage/neighbor-density signals before any steering use.",
    "validated on natural held-out objects to track known coverage/neighbor-density signals before any steering use; each component (distance-to-random, perturbation stability, SAE-coherence) is reported individually as an ablation as well as combined, and both the combination weights and the reliability-gate threshold are fixed on a held-out calibration set only, never on test."),
 ],
 "risk_append":
  " 7) Generalization: we report whether a single reliability threshold and controller transfer across properties, model sizes, and the two modalities, rather than assuming universality; a threshold that must be re-fit per setting is reported as such.",
}

# ===================== idx 15 provenance_shortcut_steering ===================
edits[15] = {
 "Abstract":
  "Steering interpretable features is the standard way to make protein and molecule generators produce a desired physical property, with success judged by a property predictor. We surface a generation-time phenomenon distinct from known dataset-leakage effects (which concern inflated PREDICTORS): a GENERATOR can satisfy a physical-property target by shifting the DATASET PROVENANCE of its output -- source organism, protein family, structural-database subset, or assay batch that co-occurs with the property in training -- rather than its physics, and interpretability lets us attribute the shortcut to specific feature directions. Training sparse autoencoders on ESM-2 and a SMILES chemical LM, we operationally separate physics-aligned directions (property correlation surviving provenance stratification) from provenance-aligned directions (high mutual information with provenance labels), predefining properties where family is plausibly causal versus clearly non-causal so the shortcut is isolable. We test three claims with pre-registered decision rules: (1) standard steering moves substantially along provenance features (a provenance-subspace displacement fraction), and its gain shrinks under a provenance-controlled oracle (a spurious-gain metric); (2) a per-generation provenance-shortcut score predicts a designer-relevant failure -- outputs collapse onto one provenance group and lose novelty, a wasted-screening cost; and (3) orthogonalizing the steering direction against provenance features preserves genuine, controlled-oracle gain while restoring novelty, validated by a synthetic planted-shortcut positive control. Baselines include standard and random-direction steering, supervised provenance classifiers, and projection-based debiasing. We deliver a provenance-shortcut audit -- usable as a reporting checklist for protein-design, molecular-generation, interpretability, and ML-for-science benchmarking -- that separates designing-the-molecule from designing-the-database. The primary high-stakes setting is protein thermostability, where a provenance shortcut wastes expensive stability screening.",
 "rw_append":
  " EXPLICIT NOVELTY CLAIMS: (1) generation-time provenance shortcuting (a GENERATOR shifts provenance to hit a property), distinct from prior leakage work on inflated PREDICTORS; (2) interpretability-mediated ATTRIBUTION of the shortcut to specific feature directions; (3) a provenance-shortcut score predicting design degeneration; (4) provenance-invariant steering as a fix, validated by a planted-shortcut positive control. Closest baselines by name: standard feature steering, random-direction steering, supervised provenance classifiers, projection/adversarial debiasing, and leakage-aware evaluation. Affected communities: protein design, molecular generation, interpretability, and ML-for-science benchmarking; the audit is intended as a reporting checklist.",
 "exp_edits": [
   ("~8 property x domain settings; 500 generations per condition.",
    "~8 property x domain settings; 500 generations per condition. FEASIBILITY/DATA: SAEs trained on ~200M activations (~1-2 GPU-days each on one A100); provenance metadata coverage -- proteins: organism/taxon and Pfam family for >95% of training objects, PDB/CATH membership for the structured subset; molecules: ChEMBL assay/document id and Bemis-Murcko scaffold for the full training set. We PREDEFINE, per property, whether provenance is plausibly CAUSAL (e.g., family-defining catalytic motifs) or clearly NON-CAUSAL-but-correlated (e.g., thermostability co-occurring with thermophile source), and analyze the two groups separately; the primary high-stakes property is protein thermostability. Layer (60% depth) and dictionary size (16384) are fixed a priori, with robustness to both reported as an ablation. A feature is called provenance-aligned only by a pre-registered rule (provenance mutual information above, and provenance-stratified property partial-correlation below, fixed thresholds) to avoid post hoc labeling."),
 ],
}

# ===================== idx 16 steering_sideeffect_law =======================
edits[16] = {
 "Abstract":
  "Steering an interpretable feature to control one property of a generated protein or molecule is the standard controllable-design paradigm, judged mainly by whether the target property moves. In text language models, steering is known to cause off-target effects, and SAE-based methods (e.g., Chalnev et al. 2024) minimize them using EMPIRICALLY-MEASURED effect vectors; but there the off-target 'property' is a fuzzy behavior and the effect must be measured per target. We make two moves. First, a new SETTING: in scientific generative models every off-target property (helix content, charge, logP, ring count, motif presence) is an objectively verifiable structural fact, so collateral drift becomes a measurable VECTOR, not a benchmark wobble. Second, a sharper QUESTION: can that drift be predicted a priori, before any generation, from the SAE dictionary geometry alone? We hypothesize each feature carries a fixed 'side-effect signature' -- computable from decoder-direction overlaps and a per-feature property-Jacobian -- that forecasts its drift vector. We frame this as a domain- and battery-specific empirical regularity, not a universal law. Using ESM-2 and a SMILES chemical LM with sparse autoencoders, we test three separable hypotheses: (1) single-target steering induces structured, non-random off-target drift under hard oracles; (2) the geometry-derived signature predicts each feature's measured drift vector, with a NO-SURROGATE decoder-overlap-only variant guarding against proxy leakage; and (3) the signature powers a pre-flight forecaster and a minimal-collateral controller (low-drift feature selection or orthogonalization) that hold non-target properties fixed, quantifying compute saved versus generation-based screening. Users and workflows: protein design, molecular optimization, and multi-property/constraint-satisfaction generative design, plus model evaluation and safety auditing of steered outputs.",
 "rw_append":
  " DELTA vs text-LLM pre-intervention side-effect prediction (Chalnev et al. 2024, SAE-Targeted Steering): they minimize side effects using effect vectors MEASURED empirically per target, whereas we predict the drift vector A PRIORI from fixed dictionary geometry (decoder overlaps + property-Jacobian) with NO generation, against HARD structural oracles. We claim a domain- and battery-specific empirical regularity, not a universal theory. Three separable contributions: (1) the finding (structured drift), (2) the predictor (geometry-derived signature), (3) the method (minimal-collateral controller); each is publishable on its own even if a later one fails.",
 "exp_edits": [
   ("500 generations per feature x strength level.",
    "500 generations per feature x strength level. SCOPE: the side-effect signature is computed PER FEATURE and predicts a drift VECTOR over the full property battery; we test whether it holds per model size, per SAE variant, and per domain, and report where it fails rather than asserting universality. All decisive thresholds below are reported with bootstrap confidence intervals over seeds."),
 ],
}

# ===================== idx 17 chirality_syntactic_shortcut ==================
edits[17] = {
 "Short Hypothesis":
  "String-based (SMILES/SELFIES) molecular generative models emit stereochemistry tokens (@/@@, E/Z) not because they possess a semantically-grounded internal representation of 3D chirality, but as a largely syntactic copy-from-context habit. We hypothesize that (i) NO compact intervention was FOUND -- under multiple intervention types, layers, and strengths -- that causally flips a stereocenter's configuration while holding the rest of the molecule fixed; (ii) instead, the model tracks a shallow 'stereo-parity bookkeeping' signal tied to local ring/branch syntax; and (iii) this makes controlled enantiomer design (asking for the R vs S form of a specified scaffold) systematically unreliable in a way ordinary validity/property checks never reveal. We keep decodability, steerability, and design-reliability as three separately-tested claims, and confirm the intervention pipeline works on a known non-chiral feature before reading any null on chirality.",
 "Abstract":
  "Chirality determines whether a drug heals or harms -- enantiomers share identical 2D connectivity yet can differ drastically in safety and potency -- and it is the one molecular property that cannot be read off a graph, requiring genuine 3D reasoning. String-based generative models (SMILES/SELFIES language models) routinely emit stereochemistry tokens (@/@@, E/Z) and pass validity checks, but whether they hold an internal, causally-manipulable representation of chirality or merely copy stereo tags as local syntax is unknown. Prior mechanistic work on molecular transformers analyzes attention and residual-stream circuits for ring/branch syntax and valence, but never causally intervenes on stereochemistry; our delta is a causal edit test that can FALSIFY a chirality representation -- showing an intervention cannot flip a stereocenter while holding the graph fixed -- which correlational attention/probe analyses cannot. Training sparse autoencoders on SMILES/SELFIES language models, we separate three claims: (1) DECODABILITY -- probe stereocenter configuration, net of a purely syntactic control probe; (2) STEERABILITY -- whether any compact intervention flips a targeted stereocenter (R->S) in the finished molecule while holding the rest of the graph, other centers, and validity fixed, with a POSITIVE CONTROL steering a known non-chiral feature (valence capacity) to prove the pipeline can steer; and (3) INTERPRETATION plus a DESIGN-RELIABILITY AUDIT -- whether located units track true CIP parity or shallow syntax, and how often requesting a specified enantiomer silently returns the wrong one, undetected by validity/likelihood. We predict no clean causal chirality handle, stereo tokens riding syntax, and silent enantiocontrol failure -- yielding a concrete pre-flight enantioreliability check, for medicinal chemists and generative-model builders, for when generated stereochemistry can be trusted. A positive (steerable handle) result is equally actionable, enabling controllable stereochemical generation.",
 "rw_append":
  " DELTA vs 'Circuits, Features, and Heuristics in Molecular Transformers' (2025): that work analyzes attention/residual-stream circuits correlationally and never intervenes on stereochemistry; our causal edit test can FALSIFY a chirality representation by showing an intervention cannot flip a stereocenter while holding the graph fixed -- something correlational analyses cannot establish. This is a new causal test, not a claim that chirality has never been studied. Three separable claims -- decodability, steerability, design-reliability -- each with its own acceptance criterion; a positive control on a known non-chiral steerable feature guards against a weak-pipeline artifact.",
 "exp_edits": [
   ("each vs random-direction and matched-non-chirality-feature controls; dose-response swept.",
    "each vs random-direction and matched-non-chirality-feature controls; dose-response swept. PIPELINE POSITIVE CONTROL: on the same molecules we steer a known NON-CHIRAL feature (valence capacity, per prior molecular-transformer mechanistic work) and require it to change the intended structural property above the random control, proving the intervention pipeline can steer before any null on chirality is interpreted as absence."),
   ("SMILES-rewriting/canonicalization that preserves the molecule",
    "SMILES-rewriting/canonicalization that preserves the molecule (random non-canonical SMILES re-enumeration via RDKit with fixed atom mapping, so the molecule and its CIP labels are provably unchanged while token order and ring-closure syntax vary)"),
 ],
}

# ===================== idx 18 symmetry_shortcut_crystal =====================
edits[18] = {
 "Abstract":
  "Symmetry is the defining property of a crystal: its space group dictates physical behavior and is the primary control knob in crystal generative models, which hard-code it or condition on it. Recent work shows conditional symmetry control can silently fail -- models emit structures lacking the requested space group. Our novelty is NOT rediscovering that mismatch but explaining it mechanistically and converting the explanation into a reusable audit. We ask: do crystal generators possess an internal, causally-manipulable representation of the requested symmetry, or satisfy the constraint through a shallow lattice/Wyckoff-copying shortcut? Using open symmetry-conditioned diffusion generators (DiffCSP++/SymmCD-style) on Materials Project data, we (1) LOCATE candidate space-group representations by probing the denoiser's activations, controlling for trivial copying of the conditioning token; (2) CAUSALLY test whether a compact intervention converts generation from space group A to B -- yielding a structure whose ACHIEVED symmetry (pymatgen SpacegroupAnalyzer over a tolerance sweep) matches B while composition and atom count are held fixed -- the operational definition of a genuine handle, distinguished from a copied conditioning signal; (3) INTERPRET whether located units encode true symmetry (invariant to equivalent cell re-descriptions and origin choices) or surface lattice/Wyckoff statistics; and (4) AUDIT reliability via the SILENT SYMMETRY-ERROR RATE and an intervention-free internal symmetry-consistency score benchmarked against likelihood, formation-energy proxies, and a simple output-side symmetry heuristic. We deliver a model-agnostic, plug-in-without-retraining symmetry-reliability audit suite plus a controlled re-description dataset, and propose a minimal reporting standard. Stakeholders: crystal-generation researchers and computational materials scientists screening generated candidates, where silent symmetry errors waste relaxation compute and corrupt downstream property assumptions.",
 "rw_append":
  " CLOSEST-PRIOR-WORK CONTRAST: (i) known failure phenomenon -- Ishii et al. 2026 report silent symmetry violation but treat it as architecture; (ii) architecture fixes -- SymmCD/DiffCSP++/WyCryst hard-code or condition symmetry; (iii) predictive-model interpretability -- CGCNN/Site-Net/RankAAE analyze property predictors, not generators; (iv) molecular shortcut-auditing -- our prior lens, here transferred to crystallographic symmetry. Setting-specific difference: crystal symmetry is a discrete, globally-defined group constraint (not a local per-token property), invariant to equivalent cell/origin re-descriptions -- so a genuine representation must be re-description-invariant, a test with no molecular analogue. Novelty is the mechanistic explanation plus a released, model-agnostic audit artifact, not the mismatch itself.",
 "exp_edits": [
   ("vs random-direction and matched-non-symmetry controls; dose-response swept.",
    "vs random-direction and matched-non-symmetry controls; dose-response swept. Causal controls are strengthened: timestep-matched random patching, layer-matched non-symmetry directions, and A-vs-B runs sharing the same random seed so only the symmetry intervention differs; composition and atom count are held fixed throughout so 'space-group switching' is unambiguous."),
   ("baselines -- generation likelihood, e-above-hull/formation-energy proxy, validity checks, and a black-box raw-activation probe;",
    "baselines -- generation likelihood, e-above-hull/formation-energy proxy, validity checks, a SIMPLE OUTPUT-SIDE SYMMETRY HEURISTIC (estimating symmetry from the partial/finished structure directly, no internals), and a black-box raw-activation probe;"),
   ("500 generations per condition.",
    "500 generations per condition. DELIVERABLE: a released model-agnostic symmetry-consistency AUDIT SUITE (usable as a plug-in pre-flight filter on existing generators without retraining) and a CONTROLLED RE-DESCRIPTION dataset (structures paired with symmetry-preserving cell/origin re-descriptions). All match rates, AUROCs, and subgroup effects are reported with bootstrap confidence intervals over >=3 seeds and multiple-comparison control across space-group strata; numeric decision thresholds below are pre-registered, and where arbitrary we also report the corresponding relative comparison and CI. Per-step denoiser activations and activation patching are confirmed extractable for the named open checkpoints via forward hooks on the denoiser network."),
 ],
}

# ===================== idx 19 relational_feature_steering ===================
edits[19] = {
 "Short Hypothesis":
  "Interpretable features of protein language models afford causal, steerable control over a protein's INTRINSIC (partner-independent) properties (fold, hydrophobicity, motifs), but no comparably compact, causally-steerable feature is FOUND -- under an expanded search over layers, token positions, schedules, and multi-feature directions -- for RELATIONAL properties: the context-dependent fact that a designed protein binds a SPECIFIED partner. We define relational steerability operationally (an intervention must raise the intended-partner interface score MORE than the best decoy, i.e. specificity, not generic bindability). We hypothesize relational control is absent, entangled with intrinsic features, or requires partner-conditioned representations, so steering toward 'binds partner X' silently degrades to generic bindability -- an unrecognized blind spot in interpretability-guided binder design.",
 "Abstract":
  "Interpretability-guided protein design steers PLM features toward desired properties -- but every demonstrated property is INTRINSIC to a single protein (fold, hydrophobicity, a local motif). Real binder design demands RELATIONAL control: producing a protein that binds a SPECIFIED partner -- a fact meaningless without the partner and, from decades of PPI research, irreducibly context-dependent. We introduce the intrinsic-vs-relational axis into interpretability-of-generation (conceptual novelty) and a partner-conditioned probing/steering audit (methodological novelty), and give an operational definition of RELATIONAL STEERABILITY: an intervention is relationally steerable only if it raises the intended-partner interface score MORE than the best decoy (specificity), not merely generic bindability. We hypothesize an intrinsic-easy/relational-hard asymmetry: compact steerable features exist for intrinsic properties, but no compact steerable feature is FOUND -- under an expanded search over layers, token positions, schedules, and multi-feature directions -- for partner-specific binding, so steering toward 'binds partner X' silently collapses to promiscuity. Using ESM-2 and an antibody PLM (p-IgGen) with sparse autoencoders, we (1) confirm intrinsic control succeeds (pipeline calibration); (2) contrast intrinsic-vs-relational steerability and measure a promiscuity-collapse rate, controlling for generic confounds (interface propensity, hydrophobicity, charge, length, disorder, foldability, novelty); (3) test whether relational information is absent, entangled, or requires partner conditioning; and (4) audit how often steered binders silently bind the wrong/any partner while validity and generic-bindability pass, scored by ESMFold-in-complex with calibrated AlphaFold-Multimer confirmation. We frame impact as changing evaluation norms and delivering reusable specificity-audit panels for therapeutic-design, biologics-engineering, and benchmark-creation communities, not as validated binder design.",
 "rw_append":
  " CONTRIBUTION BULLETS: (1) conceptual -- introduce the intrinsic-vs-relational axis into interpretability-of-generation; (2) methodological -- partner-conditioned probing/steering and an operational definition of relational steerability (specificity over the best decoy, not generic bindability); (3) empirical -- the intrinsic-easy/relational-hard asymmetry; (4) applied -- a reusable partner-specificity audit. Closest baselines contrasted: intrinsic single-property steering (assumes an internal handle exists), predictive partner-aware PPI models (never touch generator internals or steerability), and controllable binder-design methods (report bindability, not audited specificity). Scope is single-sequence PLMs specifically. The setting is not reducible to prior property steering because the label is UNDEFINED without a partner.",
 "exp_edits": [
   ("300 steered designs per target.",
    "300 steered designs per target. DATA/LABELS: partner panels and binder/non-binder labels are drawn from curated PPI datasets (experimentally-supported complexes and matched non-binders), split train/val/test with a <=30% inter-split sequence-identity cap (mmseqs2) and a 1:1 positive:negative balance; the 20 partners are held-out targets not used to fit any feature. INTERVENTION SEARCH (to justify any absence claim): before concluding no relational handle, we search multiple layers, token positions (including the prepended-partner region), steering schedules, and MULTI-FEATURE/compositional directions, not only single compact features. BASELINES beyond SAE features: supervised latent directions, activation patching from a bound-complex run, full-sequence partner-conditioned generation, and a retrieval/template control. CONFOUNDS regressed out or matched in all relational analyses: interface propensity, hydrophobicity, charge, length, disorder, foldability, and sequence novelty. RELATIONAL ORACLE: ESMFold-in-complex first pass with AlphaFold-Multimer confirmation on a calibrated subset (>=200 designs), with multiple interface scores (ipTM, interface pLDDT, contact count) reported alongside agreement/calibration analysis. All decision thresholds below are reported with bootstrap confidence intervals."),
 ],
 "risk_append":
  " 7) We frame practical impact as changing evaluation norms and releasing reusable specificity-audit panels, not as validated binder design; wet-lab or stronger external validation is out of scope, and any design claim is in-silico only. We report what is learned under each outcome -- strong relational failure, weak relational control, or successful partner-specific steering -- so a null is informative rather than merely negative.",
}

# ---- build & append, writing after each -------------------------------------
for idx in range(13, 20):
    rec = src[idx]
    e = edits[idx]
    fin = {}
    for f in FIELDS:
        fin[f] = rec[f]
    # wholesale field sets
    for f in ["Short Hypothesis", "Abstract"]:
        if f in e:
            fin[f] = e[f]
    # related work append
    if "rw_append" in e:
        fin["Related Work"] = rec["Related Work"] + e["rw_append"]
    # experiments targeted edits
    if "exp_edits" in e:
        s = rec["Experiments"]
        for old, new in e["exp_edits"]:
            s = repl(s, old, new)
        fin["Experiments"] = s
    # risk append
    if "risk_append" in e:
        fin["Risk Factors and Limitations"] = rec["Risk Factors and Limitations"] + e["risk_append"]
    # schema check: exactly seven fields, right order
    assert list(fin.keys()) == FIELDS, fin.keys()
    assert fin["Name"] == rec["Name"]
    out.append(fin)
    tmp = SLICE + ".tmp"
    with open(tmp, "w") as fh:
        json.dump(out, fh, indent=4, ensure_ascii=False)
    os.replace(tmp, SLICE)
    print(f"appended idx {idx} ({rec['Name']}); slice now {len(out)} records")

# final verification
final = json.load(open(SLICE))
assert len(final) == 10, len(final)
names_expected = [src[i]["Name"] for i in range(10, 20)]
names_got = [r["Name"] for r in final]
assert names_got == names_expected, list(zip(names_got, names_expected))
for r in final:
    assert list(r.keys()) == FIELDS, r.keys()
print("VERIFIED: 10 records, seven-field-only, names match claim_1.json[10:20]")
print("names:", names_got)
